[package]
name = "covalence-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.10.0"
either = "1.15.0"
thiserror = "2.0.17"

[dev-dependencies]
covalence = { path = "../covalence" }
