[package]
name = "covalence-core"
version = "0.1.0"
edition = "2024"

[dependencies]
covalence-data = { path = "./data" }
covalence-store = { path = "./store" }
covalence-kernel = { path = "./kernel" }

[dev-dependencies]
covalence = { path = "../covalence" }