[package]
name = "covalence-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
covalence-data = { path = "../data" }
either = "1.15.0"

[dev-dependencies]
covalence = { path = "../../covalence" }
