[package]
name = "covalence-store"
version = "0.1.0"
edition = "2024"

[dependencies]
covalence-data = { path = "../data" }
typed-generational-arena = "0.2.9"
egg = "0.10.0"
indexmap = "2.11.4"
smallvec = "1.15.1"